from requests import request


actionKey = "action"
databaseUserName = "usersDatabase.db"
registerAction = "register"
nameKey = "name"
passwordKey = "password"
successRegisterServerAnswer = "Success register"
failureRegisterServerAnswer = "Error register"
loginAction = "login"
successLoginServerAnswer = "Success login"
failureLoginServerAnswer = "Error login"
ipKey = "ip"
portKey = "port"
requestOnlineUsers = "Request:online users"
requestSetOnline = "set online"
onlineKey = "online"
requestSearchUser = "Request:search user"
failureSearchUserServerAnswer = "No user with this name or IP"
requestUserInfo = "Request:userInfo"
requestSearchUserTerminal = "Request:search user terminal"
requestChatConnect = "Request:chat connect"
chatBuddyNameKey = "chatBuddyName"
requestUpdateChat = "Update chat"
requestSendMessage = "Send message"
senderKey = "Sender"
receiverKey = "Receiver"
dataKey = "data"
messageKey = "message"
textKey = "text"
requestSendFile = "Send file"
requestOpenFile = "Open file"
fileNameKey = "fileName"